name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        build_time=$(date +%s)
        docker build . -t michaelthamm/website-prod:$build_time
        docker run --name website -d -p 5000:5000 michaelthamm/website-prod:$build_time
